title: DT Website
description: My awesome site
baseurl: "" # if deploying to root
url: "https://yourusername.github.io"

theme: jekyll-theme-primer

 

exclude:
  - backend/node_modules/**/*.md
  - node_modules
  - backend/node_modules
  - dist
  - dist-ssr
  - "*.log"
  - "*.local"
  - .vscode
  - .idea
  - .DS_Store
